name: CanuckPhoto
favicon: null
layout_spectrum: 0.16091
typography_spectrum: 0.36757958494126797
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#3e403f'
    - '#aeaeae'
    - '#848484'
    - '#6e1313'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
