name: CanuckPhoto
favicon: null
layout_spectrum: 0.16091
typography_spectrum: 0.36757958494126797
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4d4d4d'
    - '#ca0000'
    - '#7c7d81'
    - '#e5e5e5'
  brandStrength: 0.80543128028512
  lightness: 0.5407188846729696
  saturation: 0.6266150150913745
  rhythmicContrast: 0.05226891161873937
purpose: []
